name: Create ISO
on:
  workflow_dispatch:
    inputs:
      url:
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install 7zip
        run: |
          curl -o 7zip.exe https://www.7-zip.org/a/7z1900-x64.exe
          7zip.exe /S
        
      - name: Downloading UUP.zip
        run: curl -o Windows.zip ${{ github.event.inputs.url }}

      - name: Run a multi-line script
        run: |
          7z.exe x Windows.zip
          cd Windows.zip
          uup_download_windows.cmd
      
      - uses: actions/upload-artifact@v2
        with:
          name: Windows-ISO
          path: /home/runner/work/aria2workflow/aria2workflow/
      
